// Generated by scripts/prepare-web-assets.mjs. Original source assets are retained.
// SHA-256 goblin-specialists-v1.png: 6f1b995e30cb9e62e4547b22ac2408035f894b72f80fe491592ae9f2b525ca19
// SHA-256 tiny-swords-warrior-blue.png: 593a40da14b136374d55044fd3ba3ac11e621d645be9c75a2a6032741ab24c80
// SHA-256 tiny-swords-archer-blue.png: 0a2e1efff6d653d32777b99ca01f9018fbf27080f2aff645f0fafde175e8b7ec
// SHA-256 tiny-monk/Idle.png: a72cc63be3151c3af61e8f8c86129b8a0c563c8731e04ae89a27e616bb6cb962
import type { UnitType } from './units.ts';

export interface UnitImageUrls { portrait: string; art: string }

export const UNIT_IMAGES = new Map<UnitType, UnitImageUrls>([
  ['swordsman', { portrait: new URL('./assets/web/swordsman-portrait.png', import.meta.url).href, art: new URL('./assets/web/swordsman-art.png', import.meta.url).href }],
  ['archer', { portrait: new URL('./assets/web/archer-portrait.png', import.meta.url).href, art: new URL('./assets/web/archer-art.png', import.meta.url).href }],
  ['healer', { portrait: new URL('./assets/web/healer-portrait.png', import.meta.url).href, art: new URL('./assets/web/healer-art.png', import.meta.url).href }],
]);
