import type { SheetArtUrls, SpriteGeometry, SpriteRect } from './art-types.ts';
import type { PaletteRank } from './unit-ranks.ts';
import type { Point } from './field.ts';

// Exact approved frame geometry; generated by scripts/prepare-elf-healer-art.mjs.
export const ELF_HEALER_RENDER_HEIGHT = 35;
export const ELF_HEALER_ASSETS: Readonly<Record<PaletteRank, SheetArtUrls>> = Object.freeze({
  1: { sheet: new URL('./assets/elf-healer/elf-healer-green.webp', import.meta.url).href, art: new URL('./assets/recruitment/elf-healer.webp', import.meta.url).href },
  2: { sheet: new URL('./assets/elf-healer/elf-healer-purple.webp', import.meta.url).href, art: new URL('./assets/elf-healer/elf-healer-purple-art.webp', import.meta.url).href },
  3: { sheet: new URL('./assets/elf-healer/elf-healer-red.webp', import.meta.url).href, art: new URL('./assets/elf-healer/elf-healer-red-art.webp', import.meta.url).href },
  4: { sheet: new URL('./assets/elf-healer/elf-healer-gold.webp', import.meta.url).href, art: new URL('./assets/elf-healer/elf-healer-gold-art.webp', import.meta.url).href },
  5: { sheet: new URL('./assets/elf-healer/elf-healer-black.webp', import.meta.url).href, art: new URL('./assets/elf-healer/elf-healer-black-art.webp', import.meta.url).href },
});
export const ELF_HEALER_GEOMETRY = {
  "layout": {
    "columns": 4,
    "rows": 4
  },
  "bodyHeight": 0.75,
  "baselines": [
    0.921875,
    0.921875,
    0.921875,
    0.921875,
    0.890625,
    0.890625,
    0.890625,
    0.890625,
    0.8671875,
    0.8671875,
    0.8671875,
    0.8671875,
    0.78125,
    0.78125,
    0.78125,
    0.78125
  ],
  "centers": [
    0.5703125,
    0.5546875,
    0.5390625,
    0.515625,
    0.5703125,
    0.5546875,
    0.5390625,
    0.515625,
    0.5625,
    0.5703125,
    0.5546875,
    0.53125,
    0.5546875,
    0.5390625,
    0.53125,
    0.46875
  ],
  "sourceRects": {
    "0": {
      "x": 0,
      "y": 0,
      "width": 130,
      "height": 132
    },
    "1": {
      "x": 130,
      "y": 0,
      "width": 124,
      "height": 132
    },
    "2": {
      "x": 254,
      "y": 0,
      "width": 126,
      "height": 132
    },
    "3": {
      "x": 380,
      "y": 0,
      "width": 132,
      "height": 132
    },
    "4": {
      "x": 0,
      "y": 132,
      "width": 130,
      "height": 124
    },
    "5": {
      "x": 130,
      "y": 132,
      "width": 126,
      "height": 124
    },
    "6": {
      "x": 256,
      "y": 132,
      "width": 125,
      "height": 124
    },
    "7": {
      "x": 381,
      "y": 132,
      "width": 131,
      "height": 124
    },
    "8": {
      "x": 0,
      "y": 256,
      "width": 131,
      "height": 124
    },
    "9": {
      "x": 131,
      "y": 256,
      "width": 129,
      "height": 124
    },
    "10": {
      "x": 260,
      "y": 256,
      "width": 126,
      "height": 124
    },
    "11": {
      "x": 386,
      "y": 256,
      "width": 126,
      "height": 124
    },
    "12": {
      "x": 0,
      "y": 380,
      "width": 128,
      "height": 132
    },
    "13": {
      "x": 128,
      "y": 380,
      "width": 126,
      "height": 132
    },
    "14": {
      "x": 254,
      "y": 380,
      "width": 123,
      "height": 132
    },
    "15": {
      "x": 377,
      "y": 380,
      "width": 135,
      "height": 132
    }
  }
} satisfies SpriteGeometry;
// Keep this small optional atlas out of the initial JavaScript download.
export const ELF_HEAL_PULSE_IMAGE_URL = new URL('./assets/elf-healer/elf-healer-pulse.webp?no-inline', import.meta.url).href;
export const ELF_HEAL_PULSE_FRAMES = [
  {
    "rect": {
      "x": 0,
      "y": 0,
      "width": 64,
      "height": 64
    },
    "groundAnchor": {
      "x": 35,
      "y": 55
    }
  },
  {
    "rect": {
      "x": 64,
      "y": 0,
      "width": 64,
      "height": 64
    },
    "groundAnchor": {
      "x": 29,
      "y": 55
    }
  },
  {
    "rect": {
      "x": 0,
      "y": 64,
      "width": 64,
      "height": 64
    },
    "groundAnchor": {
      "x": 36,
      "y": 41
    }
  },
  {
    "rect": {
      "x": 64,
      "y": 64,
      "width": 64,
      "height": 64
    },
    "groundAnchor": {
      "x": 29,
      "y": 41
    }
  }
] satisfies readonly { rect: SpriteRect; groundAnchor: Point }[];
