import type { SheetArtUrls, SpriteGeometry } from './art-types.ts';
import type { PaletteRank } from './unit-ranks.ts';

// Exact approved frame geometry; generated by scripts/prepare-unicorn-art.mjs.
export const UNICORN_RENDER_HEIGHT = 47;
export const UNICORN_ASSETS: Readonly<Record<PaletteRank, SheetArtUrls>> = Object.freeze({
  1: { sheet: new URL('./assets/unicorn/unicorn-green.webp', import.meta.url).href, art: new URL('./assets/recruitment/unicorn.webp', import.meta.url).href },
  2: { sheet: new URL('./assets/unicorn/unicorn-purple.webp', import.meta.url).href, art: new URL('./assets/unicorn/unicorn-purple-art.webp', import.meta.url).href },
  3: { sheet: new URL('./assets/unicorn/unicorn-red.webp', import.meta.url).href, art: new URL('./assets/unicorn/unicorn-red-art.webp', import.meta.url).href },
  4: { sheet: new URL('./assets/unicorn/unicorn-gold.webp', import.meta.url).href, art: new URL('./assets/unicorn/unicorn-gold-art.webp', import.meta.url).href },
  5: { sheet: new URL('./assets/unicorn/unicorn-black.webp', import.meta.url).href, art: new URL('./assets/unicorn/unicorn-black-art.webp', import.meta.url).href },
});
export const UNICORN_GEOMETRY = {
  "layout": {
    "columns": 4,
    "rows": 4
  },
  "bodyHeight": 0.546875,
  "baselines": [
    0.8203125,
    0.8203125,
    0.8203125,
    0.8203125,
    0.78125,
    0.78125,
    0.78125,
    0.78125,
    0.75,
    0.75,
    0.75,
    0.75,
    0.671875,
    0.671875,
    0.671875,
    0.6875
  ],
  "centers": [
    0.5,
    0.5,
    0.4921875,
    0.5078125,
    0.515625,
    0.5,
    0.5,
    0.515625,
    0.515625,
    0.5,
    0.53125,
    0.5078125,
    0.515625,
    0.515625,
    0.515625,
    0.5
  ],
  "sourceRects": {
    "0": {
      "x": 0,
      "y": 0,
      "width": 127,
      "height": 132
    },
    "1": {
      "x": 127,
      "y": 0,
      "width": 127,
      "height": 132
    },
    "2": {
      "x": 254,
      "y": 0,
      "width": 129,
      "height": 132
    },
    "3": {
      "x": 383,
      "y": 0,
      "width": 129,
      "height": 132
    },
    "4": {
      "x": 0,
      "y": 132,
      "width": 128,
      "height": 124
    },
    "5": {
      "x": 128,
      "y": 132,
      "width": 128,
      "height": 124
    },
    "6": {
      "x": 256,
      "y": 132,
      "width": 128,
      "height": 124
    },
    "7": {
      "x": 384,
      "y": 132,
      "width": 128,
      "height": 124
    },
    "8": {
      "x": 0,
      "y": 256,
      "width": 126,
      "height": 116
    },
    "9": {
      "x": 126,
      "y": 256,
      "width": 132,
      "height": 116
    },
    "10": {
      "x": 258,
      "y": 256,
      "width": 132,
      "height": 116
    },
    "11": {
      "x": 390,
      "y": 256,
      "width": 122,
      "height": 116
    },
    "12": {
      "x": 0,
      "y": 372,
      "width": 128,
      "height": 140
    },
    "13": {
      "x": 128,
      "y": 372,
      "width": 130,
      "height": 140
    },
    "14": {
      "x": 258,
      "y": 372,
      "width": 127,
      "height": 140
    },
    "15": {
      "x": 385,
      "y": 372,
      "width": 127,
      "height": 140
    }
  }
} satisfies SpriteGeometry;
