import { UPGRADE_STAT_MULTIPLIER, type BoardSlot, type CardDefinition, type CardId, type UnitStats } from "./types";

export const CARD_DEFINITIONS: readonly CardDefinition[] = [
  {
    id: "iron_guard",
    name: "Iron Guard",
    role: "tank",
    tags: ["warrior", "guardian"],
    tier: 1,
    stats: { attack: 2, hp: 14, speed: 4, range: 1 },
    abilityId: "shield_wall",
    cardText: "Starts with shield.",
    summary: "Starts with a small shield.",
  },
  {
    id: "shieldbearer",
    name: "Shieldbearer",
    role: "tank",
    tags: ["guardian"],
    tier: 1,
    stats: { attack: 0, hp: 16, speed: 3, range: 1 },
    abilityId: "bulwark",
    cardText: "Taunts and blocks hits.",
    summary: "Front row only. Taunts and may fully block hits.",
  },
  {
    id: "boar_rider",
    name: "Boar Rider",
    role: "striker",
    tags: ["warrior", "beast"],
    tier: 1,
    stats: { attack: 4, hp: 10, speed: 5, range: 1 },
    abilityId: "charge",
    cardText: "Bonus first hit.",
    summary: "Deals extra damage on the first attack.",
  },
  {
    id: "sneakblade",
    name: "Sneakblade",
    role: "striker",
    tags: ["rogue"],
    tier: 1,
    stats: { attack: 4, hp: 7, speed: 7, range: 1 },
    abilityId: "backstab",
    cardText: "Targets weakest enemy.",
    summary: "Targets the weakest enemy.",
  },
  {
    id: "spear_recruit",
    name: "Spear Recruit",
    role: "striker",
    tags: ["warrior"],
    tier: 1,
    stats: { attack: 3, hp: 9, speed: 5, range: 2 },
    abilityId: "none",
    cardText: "Simple reach fighter.",
    summary: "Simple reach fighter.",
  },
  {
    id: "longbow_hunter",
    name: "Longbow Hunter",
    role: "ranged",
    tags: ["rogue"],
    tier: 1,
    stats: { attack: 3, hp: 7, speed: 6, range: 3 },
    abilityId: "snipe",
    cardText: "Shoots lowest HP.",
    summary: "Shoots the lowest HP enemy.",
  },
  {
    id: "ember_mage",
    name: "Ember Mage",
    role: "caster",
    tags: ["mage"],
    tier: 1,
    stats: { attack: 2, hp: 6, speed: 5, range: 3 },
    abilityId: "fireball",
    cardText: "Splashes nearby slots.",
    summary: "Fireball damages the target and splashes adjacent slots.",
  },
  {
    id: "frost_acolyte",
    name: "Frost Acolyte",
    role: "caster",
    tags: ["mage"],
    tier: 2,
    stats: { attack: 2, hp: 8, speed: 4, range: 3 },
    abilityId: "frost_hex",
    cardText: "First hit weakens ATK.",
    summary: "First hit weakens the target's attack.",
  },
  {
    id: "grave_binder",
    name: "Grave Binder",
    role: "caster",
    tags: ["undead", "mage"],
    tier: 2,
    stats: { attack: 2, hp: 7, speed: 4, range: 3 },
    abilityId: "bone_pact",
    cardText: "Returns as skeleton.",
    summary: "Returns once as a weak skeleton.",
  },
  {
    id: "bone_soldier",
    name: "Bone Soldier",
    role: "tank",
    tags: ["undead", "warrior"],
    tier: 1,
    stats: { attack: 3, hp: 10, speed: 4, range: 1 },
    abilityId: "none",
    cardText: "Reliable bruiser.",
    summary: "Reliable undead bruiser.",
  },
  {
    id: "witch_doctor",
    name: "Witch Doctor",
    role: "support",
    tags: ["beast", "mage"],
    tier: 2,
    stats: { attack: 2, hp: 9, speed: 4, range: 3 },
    abilityId: "heal_ally",
    cardText: "Heals, then attacks.",
    summary: "Heals the weakest ally before attacking.",
  },
  {
    id: "field_cleric",
    name: "Field Cleric",
    role: "support",
    tags: ["guardian"],
    tier: 1,
    stats: { attack: 1, hp: 8, speed: 4, range: 2 },
    abilityId: "heal_only",
    cardText: "Heals instead of attacking.",
    summary: "Heals an ally instead of attacking.",
  },
  {
    id: "wolfhound",
    name: "Wolfhound",
    role: "striker",
    tags: ["beast"],
    tier: 1,
    stats: { attack: 4, hp: 7, speed: 8, range: 1 },
    abilityId: "pack_hunter",
    cardText: "Gains power near beasts.",
    summary: "Gets stronger when another beast is present.",
  },
  {
    id: "thorn_druid",
    name: "Thorn Druid",
    role: "support",
    tags: ["beast", "mage"],
    tier: 2,
    stats: { attack: 2, hp: 10, speed: 4, range: 2 },
    abilityId: "thorn_guard",
    cardText: "Shields allies at start.",
    summary: "Grants shield to allies at combat start.",
  },
  {
    id: "stone_golem",
    name: "Stone Golem",
    role: "tank",
    tags: ["guardian"],
    tier: 3,
    stats: { attack: 2, hp: 20, speed: 2, range: 1 },
    abilityId: "stone_skin",
    cardText: "Slow and hard to kill.",
    summary: "Very slow, very hard to kill.",
  },
  {
    id: "pyromancer",
    name: "Pyromancer",
    role: "caster",
    tags: ["mage"],
    tier: 3,
    stats: { attack: 3, hp: 7, speed: 5, range: 3 },
    abilityId: "pyro_splash",
    cardText: "Stronger splash spell.",
    summary: "Stronger splash spell.",
  },
  {
    id: "duelist",
    name: "Duelist",
    role: "striker",
    tags: ["rogue", "warrior"],
    tier: 2,
    stats: { attack: 5, hp: 8, speed: 6, range: 1 },
    abilityId: "riposte",
    cardText: "Starts shielded.",
    summary: "Starts with shield and hits hard.",
  },
  {
    id: "banner_knight",
    name: "Banner Knight",
    role: "support",
    tags: ["warrior", "guardian"],
    tier: 2,
    stats: { attack: 2, hp: 11, speed: 3, range: 1 },
    abilityId: "battle_banner",
    cardText: "Buffs allied attack.",
    summary: "Buffs allied attack at combat start.",
  },
];

export const CARD_BY_ID: Readonly<Record<CardId, CardDefinition>> = Object.fromEntries(
  CARD_DEFINITIONS.map((card) => [card.id, card]),
) as Record<CardId, CardDefinition>;

export function getCardDefinition(cardId: CardId): CardDefinition {
  return CARD_BY_ID[cardId];
}

export function getCardStatsForUpgrade(card: CardDefinition, upgradeLevel: BoardSlot["upgradeLevel"]): UnitStats {
  if (upgradeLevel <= 0) {
    return { ...card.stats };
  }

  return {
    ...card.stats,
    attack: card.stats.attack * UPGRADE_STAT_MULTIPLIER,
    hp: card.stats.hp * UPGRADE_STAT_MULTIPLIER,
  };
}
