import { UPGRADE_STAT_MULTIPLIER, type BoardSlot, type CardDefinition, type CardId, type UnitStats } from "./types";

export const CARD_DEFINITIONS: readonly CardDefinition[] = [
  {
    id: "iron_guard",
    name: "Iron Guard",
    role: "tank",
    tags: ["warrior", "guardian"],
    tier: 1,
    stats: { attack: 2, hp: 14, speed: 4, range: 1 },
    abilityId: "shield_wall",
    cardText: "Starts with 3 armor.",
    summary: "Starts combat with 3 armor that absorbs incoming damage.",
  },
  {
    id: "shieldbearer",
    name: "Shieldbearer",
    role: "tank",
    tags: ["guardian"],
    tier: 1,
    stats: { attack: 0, hp: 16, speed: 3, range: 1 },
    abilityId: "bulwark",
    cardText: "Taunts and blocks hits.",
    summary: "Front row only. Taunts and may fully block hits.",
  },
  {
    id: "boar_rider",
    name: "Boar Rider",
    role: "striker",
    tags: ["warrior", "beast"],
    tier: 1,
    stats: { attack: 4, hp: 10, speed: 5, range: 1 },
    abilityId: "charge",
    cardText: "Bonus first hit.",
    summary: "Deals extra damage on the first attack.",
  },
  {
    id: "sneakblade",
    name: "Sneakblade",
    role: "striker",
    tags: ["rogue"],
    tier: 1,
    stats: { attack: 4, hp: 7, speed: 7, range: 1 },
    abilityId: "backstab",
    cardText: "Targets weakest enemy.",
    summary: "Targets the weakest enemy.",
  },
  {
    id: "spear_recruit",
    name: "Spear Recruit",
    role: "striker",
    tags: ["warrior"],
    tier: 1,
    stats: { attack: 3, hp: 9, speed: 5, range: 2 },
    abilityId: "none",
    cardText: "Simple and reliable fighter.",
    summary: "Simple and reliable fighter.",
  },
  {
    id: "longbow_hunter",
    name: "Longbow Hunter",
    role: "ranged",
    tags: ["rogue"],
    tier: 1,
    stats: { attack: 3, hp: 7, speed: 6, range: 3 },
    abilityId: "snipe",
    cardText: "Shoots lowest HP.",
    summary: "Shoots the lowest HP enemy.",
  },
  {
    id: "ember_mage",
    name: "Ember Mage",
    role: "caster",
    tags: ["mage"],
    tier: 1,
    stats: { attack: 2, hp: 6, speed: 5, range: 3 },
    abilityId: "fireball",
    cardText: "Splashes nearby slots.",
    summary: "Fireball damages the target and splashes adjacent slots.",
  },
  {
    id: "frost_acolyte",
    name: "Frost Acolyte",
    role: "caster",
    tags: ["mage"],
    tier: 2,
    stats: { attack: 2, hp: 8, speed: 4, range: 3 },
    abilityId: "frost_hex",
    cardText: "First hit weakens ATK.",
    summary: "First hit weakens the target's attack.",
  },
  {
    id: "grave_binder",
    name: "Grave Binder",
    role: "caster",
    tags: ["undead", "mage"],
    tier: 2,
    stats: { attack: 2, hp: 7, speed: 4, range: 3 },
    abilityId: "bone_pact",
    cardText: "Returns as a 2/4 skeleton; upgraded: 3/6.",
    summary: "Returns once as a 2 ATK / 4 HP skeleton; upgraded: 3 ATK / 6 HP.",
  },
  {
    id: "bone_soldier",
    name: "Bone Soldier",
    role: "tank",
    tags: ["undead", "warrior"],
    tier: 1,
    stats: { attack: 3, hp: 10, speed: 4, range: 1 },
    abilityId: "none",
    cardText: "Reliable bruiser.",
    summary: "Reliable undead bruiser.",
  },
  {
    id: "witch_doctor",
    name: "Witch Doctor",
    role: "support",
    tags: ["beast", "mage"],
    tier: 2,
    stats: { attack: 2, hp: 9, speed: 4, range: 3 },
    abilityId: "heal_ally",
    cardText: "Heals, then attacks.",
    summary: "Heals the weakest ally before attacking.",
  },
  {
    id: "field_cleric",
    name: "Field Cleric",
    role: "support",
    tags: ["guardian"],
    tier: 1,
    stats: { attack: 1, hp: 8, speed: 4, range: 2 },
    abilityId: "heal_only",
    cardText: "Heals instead of attacking.",
    summary: "Heals an ally instead of attacking.",
  },
  {
    id: "wolfhound",
    name: "Wolfhound",
    role: "striker",
    tags: ["beast"],
    tier: 1,
    stats: { attack: 4, hp: 7, speed: 8, range: 1 },
    abilityId: "pack_hunter",
    cardText: "Gains power near beasts.",
    summary: "Gets stronger when another beast is present.",
  },
  {
    id: "thorn_druid",
    name: "Thorn Druid",
    role: "support",
    tags: ["beast", "mage"],
    tier: 2,
    stats: { attack: 2, hp: 10, speed: 4, range: 2 },
    abilityId: "thorn_guard",
    cardText: "Grants allies 1 armor at start.",
    summary: "Grants every ally 1 armor at combat start.",
  },
  {
    id: "stone_golem",
    name: "Stone Golem",
    role: "tank",
    tags: ["guardian"],
    tier: 3,
    stats: { attack: 2, hp: 20, speed: 2, range: 1 },
    abilityId: "stone_skin",
    cardText: "Starts with 5 armor.",
    summary: "Very slow and durable; starts combat with 5 armor.",
  },
  {
    id: "pyromancer",
    name: "Pyromancer",
    role: "caster",
    tags: ["mage"],
    tier: 3,
    stats: { attack: 3, hp: 7, speed: 5, range: 3 },
    abilityId: "pyro_splash",
    cardText: "Stronger splash spell.",
    summary: "Stronger splash spell.",
  },
  {
    id: "duelist",
    name: "Duelist",
    role: "striker",
    tags: ["rogue", "warrior"],
    tier: 2,
    stats: { attack: 5, hp: 8, speed: 6, range: 1 },
    abilityId: "riposte",
    cardText: "Starts with 2 armor.",
    summary: "Starts combat with 2 armor and hits hard.",
  },
  {
    id: "banner_knight",
    name: "Banner Knight",
    role: "support",
    tags: ["warrior", "guardian"],
    tier: 2,
    stats: { attack: 2, hp: 11, speed: 3, range: 1 },
    abilityId: "battle_banner",
    cardText: "Buffs allied attack.",
    summary: "Buffs allied attack at combat start.",
  },
  {
    id: "bone_archer",
    name: "Bone Archer",
    role: "ranged",
    tags: ["undead", "rogue"],
    tier: 1,
    stats: { attack: 3, hp: 6, speed: 5, range: 3 },
    abilityId: "snipe",
    cardText: "Targets the lowest-HP enemy.",
    summary: "Attacks the enemy with the lowest current HP.",
  },
  {
    id: "plague_rat",
    name: "Plague Rat",
    role: "striker",
    tags: ["beast", "undead"],
    tier: 1,
    stats: { attack: 3, hp: 7, speed: 8, range: 1 },
    abilityId: "pack_hunter",
    cardText: "Gets +1 ATK if another Beast is present.",
    summary: "At combat start, gains +1 ATK if the army has another Beast.",
  },
  {
    id: "rune_warden",
    name: "Rune Warden",
    role: "caster",
    tags: ["mage", "guardian"],
    tier: 1,
    stats: { attack: 2, hp: 9, speed: 4, range: 3 },
    abilityId: "shield_wall",
    cardText: "Starts combat with 3 armor.",
    summary: "Starts combat with 3 armor that absorbs incoming damage.",
  },
  {
    id: "forest_skirmisher",
    name: "Forest Skirmisher",
    role: "ranged",
    tags: ["beast"],
    tier: 1,
    stats: { attack: 3, hp: 7, speed: 7, range: 3 },
    abilityId: "charge",
    cardText: "The first shot deals 2 extra damage.",
    summary: "Its first attack deals 2 extra damage.",
  },
  {
    id: "marsh_stalker",
    name: "Marsh Stalker",
    role: "ranged",
    tags: ["beast", "rogue"],
    tier: 2,
    stats: { attack: 3, hp: 8, speed: 6, range: 2 },
    abilityId: "backstab",
    cardText: "Targets the lowest-HP enemy; first hit deals 1 extra damage.",
    summary: "Hunts the enemy with the lowest current HP, and its first attack deals 1 extra damage.",
  },
  {
    id: "crypt_keeper",
    name: "Crypt Keeper",
    role: "support",
    tags: ["undead", "guardian"],
    tier: 2,
    stats: { attack: 1, hp: 11, speed: 4, range: 2 },
    abilityId: "heal_only",
    cardText: "Restores up to 2 HP instead of attacking.",
    summary: "Instead of attacking, restores up to 2 HP to the weakest wounded ally.",
  },
  {
    id: "battle_alchemist",
    name: "Battle Alchemist",
    role: "support",
    tags: ["warrior", "mage"],
    tier: 2,
    stats: { attack: 3, hp: 8, speed: 5, range: 2 },
    abilityId: "heal_ally",
    cardText: "Restores up to 2 HP, then attacks.",
    summary: "Before attacking, restores up to 2 HP to the weakest wounded ally.",
  },
  {
    id: "night_warden",
    name: "Night Warden",
    role: "tank",
    tags: ["rogue", "guardian"],
    tier: 2,
    stats: { attack: 3, hp: 12, speed: 5, range: 1 },
    abilityId: "riposte",
    cardText: "Starts combat with 2 armor.",
    summary: "Starts combat with 2 armor that absorbs incoming damage.",
  },
  {
    id: "grave_raider",
    name: "Grave Raider",
    role: "striker",
    tags: ["undead", "warrior"],
    tier: 3,
    stats: { attack: 5, hp: 11, speed: 5, range: 1 },
    abilityId: "charge",
    cardText: "The first hit deals 2 extra damage.",
    summary: "Its first attack deals 2 extra damage.",
  },
  {
    id: "frost_wraith",
    name: "Frost Wraith",
    role: "caster",
    tags: ["undead", "rogue"],
    tier: 3,
    stats: { attack: 3, hp: 9, speed: 6, range: 3 },
    abilityId: "frost_hex",
    cardText: "The first hit reduces the target's ATK by 1.",
    summary: "Its first attack reduces the target's ATK by 1, to a minimum of 1.",
  },
  {
    id: "ironhide_bear",
    name: "Ironhide Bear",
    role: "tank",
    tags: ["beast"],
    tier: 3,
    stats: { attack: 3, hp: 18, speed: 3, range: 1 },
    abilityId: "thorn_guard",
    cardText: "Gives every ally 1 armor at combat start.",
    summary: "At combat start, every ally receives 1 armor.",
  },
  {
    id: "soul_hunter",
    name: "Soul Hunter",
    role: "ranged",
    tags: ["undead"],
    tier: 3,
    stats: { attack: 5, hp: 9, speed: 5, range: 3 },
    abilityId: "backstab",
    cardText: "Targets the lowest-HP enemy; first hit deals 1 extra damage.",
    summary: "Hunts the enemy with the lowest current HP, and its first attack deals 1 extra damage.",
  },
  {
    id: "city_crossbowman",
    name: "Citadel Crossbowman",
    role: "ranged",
    tags: ["guardian"],
    tier: 1,
    stats: { attack: 3, hp: 8, speed: 4, range: 3 },
    abilityId: "snipe",
    cardText: "Targets the lowest-HP enemy.",
    summary: "Attacks the enemy with the lowest current HP.",
  },
  {
    id: "harpy_scout",
    name: "Harpy Scout",
    role: "ranged",
    tags: ["beast", "rogue"],
    tier: 1,
    stats: { attack: 3, hp: 6, speed: 8, range: 3 },
    abilityId: "pack_hunter",
    cardText: "Gets +1 ATK if another Beast is present.",
    summary: "At combat start, gains +1 ATK if the army has another Beast.",
  },
  {
    id: "smoke_trickster",
    name: "Smoke Trickster",
    role: "caster",
    tags: ["rogue", "mage"],
    tier: 1,
    stats: { attack: 2, hp: 7, speed: 7, range: 2 },
    abilityId: "frost_hex",
    cardText: "The first hit reduces the target's ATK by 1.",
    summary: "Its first attack reduces the target's ATK by 1, to a minimum of 1.",
  },
  {
    id: "war_mastiff",
    name: "War Mastiff",
    role: "tank",
    tags: ["beast", "warrior"],
    tier: 1,
    stats: { attack: 2, hp: 13, speed: 6, range: 1 },
    abilityId: "shield_wall",
    cardText: "Starts combat with 3 armor.",
    summary: "Starts combat with 3 armor that absorbs incoming damage.",
  },
  {
    id: "grave_bellringer",
    name: "Grave Bellringer",
    role: "support",
    tags: ["undead", "guardian"],
    tier: 2,
    stats: { attack: 2, hp: 10, speed: 3, range: 2 },
    abilityId: "battle_banner",
    cardText: "Gives every other ally +1 ATK at combat start.",
    summary: "At combat start, every other ally gains +1 ATK.",
  },
  {
    id: "moon_priestess",
    name: "Moon Priestess",
    role: "support",
    tags: ["mage", "guardian"],
    tier: 2,
    stats: { attack: 2, hp: 8, speed: 5, range: 3 },
    abilityId: "heal_ally",
    cardText: "Restores up to 2 HP, then attacks.",
    summary: "Before attacking, restores up to 2 HP to the lowest-HP wounded ally.",
  },
  {
    id: "phantom_duelist",
    name: "Phantom Duelist",
    role: "striker",
    tags: ["undead", "rogue"],
    tier: 2,
    stats: { attack: 4, hp: 9, speed: 7, range: 1 },
    abilityId: "riposte",
    cardText: "Starts combat with 2 armor.",
    summary: "Starts combat with 2 armor that absorbs incoming damage.",
  },
  {
    id: "siege_engineer",
    name: "Siege Engineer",
    role: "ranged",
    tags: ["warrior", "rogue"],
    tier: 2,
    stats: { attack: 3, hp: 8, speed: 3, range: 3 },
    abilityId: "fireball",
    cardText: "Deals 1 damage to enemies adjacent to the target.",
    summary: "Each attack also deals 1 damage to enemies in slots adjacent to the target.",
  },
  {
    id: "bronze_minotaur",
    name: "Bronze Minotaur",
    role: "tank",
    tags: ["beast"],
    tier: 3,
    stats: { attack: 3, hp: 18, speed: 3, range: 1 },
    abilityId: "stone_skin",
    cardText: "Starts combat with 5 armor.",
    summary: "Starts combat with 5 armor that absorbs incoming damage.",
  },
  {
    id: "headless_knight",
    name: "Headless Knight",
    role: "striker",
    tags: ["undead"],
    tier: 3,
    stats: { attack: 6, hp: 10, speed: 6, range: 1 },
    abilityId: "charge",
    cardText: "The first hit deals 2 extra damage.",
    summary: "Its first attack deals 2 extra damage.",
  },
  {
    id: "star_seer",
    name: "Star Seer",
    role: "caster",
    tags: ["mage"],
    tier: 3,
    stats: { attack: 4, hp: 10, speed: 4, range: 3 },
    abilityId: "snipe",
    cardText: "Targets the lowest-HP enemy.",
    summary: "Attacks the enemy with the lowest current HP.",
  },
  {
    id: "war_chaplain",
    name: "War Chaplain",
    role: "support",
    tags: ["warrior"],
    tier: 3,
    stats: { attack: 2, hp: 13, speed: 3, range: 2 },
    abilityId: "thorn_guard",
    cardText: "Gives every ally 1 armor at combat start.",
    summary: "At combat start, every ally receives 1 armor.",
  },
];

export const CARD_BY_ID: Readonly<Record<CardId, CardDefinition>> = Object.fromEntries(
  CARD_DEFINITIONS.map((card) => [card.id, card]),
) as Record<CardId, CardDefinition>;

export function getCardDefinition(cardId: CardId): CardDefinition {
  return CARD_BY_ID[cardId];
}

export function getCardStatsForUpgrade(card: CardDefinition, upgradeLevel: BoardSlot["upgradeLevel"]): UnitStats {
  if (upgradeLevel <= 0) {
    return { ...card.stats };
  }

  return {
    ...card.stats,
    attack: card.stats.attack * UPGRADE_STAT_MULTIPLIER,
    hp: card.stats.hp * UPGRADE_STAT_MULTIPLIER,
  };
}
