export const GAME_WIDTH = 430;
export const GAME_HEIGHT = 764;

export const DEFAULT_STAGE_ORIGIN_X = 215;
export const DEFAULT_STAGE_ORIGIN_Y = 520;
export const DEFAULT_PLAYER_STAGE_X = -130;
export const DEFAULT_PLAYER_STAGE_Y = 159;
export const DEFAULT_ENEMY_STAGE_X = 130;
export const DEFAULT_ENEMY_STAGE_Y = 223;
export const DEFAULT_PLAYER_SCALE = 0.78;
export const DEFAULT_ENEMY_SCALE = 1;
export const DEFAULT_ACTION_ARC_ROTATION = 71;
export const DEFAULT_ACTION_ARC_RADIUS = 72;
export const DEFAULT_ACTION_BUTTON_SCALE = 0.63;
export const DEFAULT_ACTION_FORWARD_ANGLE = -100;
export const DEFAULT_ACTION_BACK_ANGLE = 138;
export const DEFAULT_ACTION_LUNGE_ANGLE = -34;
export const DEFAULT_ACTION_LIGHT_ANGLE = -22;
export const DEFAULT_ACTION_MEDIUM_ANGLE = -74;
export const DEFAULT_ACTION_HEAVY_ANGLE = -125;
export const DEFAULT_ACTION_TAUNT_ANGLE = 74;
export const DEFAULT_ACTION_REST_ANGLE = 74;

export const GROUND_Y = DEFAULT_STAGE_ORIGIN_Y;
export const FIGHTER_BASE_Y = DEFAULT_STAGE_ORIGIN_Y - 132;

export const PLAYER_BASE_X = DEFAULT_STAGE_ORIGIN_X + DEFAULT_PLAYER_STAGE_X;
export const ENEMY_BASE_X = DEFAULT_STAGE_ORIGIN_X + DEFAULT_ENEMY_STAGE_X;
export const POSITION_PIXEL_STEP = 72;

export const ARENA_WORLD_PADDING_X = 0;
export const ARENA_WORLD_LEFT = -ARENA_WORLD_PADDING_X;
export const ARENA_WORLD_WIDTH = GAME_WIDTH + ARENA_WORLD_PADDING_X * 2;

export const CAMERA_PLAYER_SCREEN_X = 150;
export const START_PLAYER_SCREEN_X = DEFAULT_STAGE_ORIGIN_X + DEFAULT_PLAYER_STAGE_X;
export const START_ENEMY_SCREEN_X = DEFAULT_STAGE_ORIGIN_X + DEFAULT_ENEMY_STAGE_X;
export const FAR_CAMERA_ZOOM = 1;
export const CLOSE_CAMERA_ZOOM = 1.14;
export const CAMERA_CENTER_Y = 430;

export const OVERVIEW_DISTANCE = 3;
export const OVERVIEW_MIN_ZOOM = 1;
export const OVERVIEW_MAX_ZOOM = 1;
export const OVERVIEW_SCREEN_PADDING = 28;

