export const RANDOM_ARENA_OPPONENT_NAMES = [
  "Grubbo",
  "Marn",
  "Brakk",
  "Tull",
  "Veso",
  "Narg",
  "Dott",
  "Klem",
  "Rusk",
  "Bendo",
  "Farlo",
  "Mott",
  "Harn",
  "Skiv",
  "Orlo",
  "Gann",
  "Palk",
  "Dravo",
  "Nemm",
  "Vark",
  "Dust Grit",
  "Sand Mutt",
  "Red Paver",
  "Pit Noll",
  "Ashback",
  "Mud Heel",
  "Dune Rat",
  "Gravel Tom",
  "Soot Jax",
  "Clayborn",
  "Rustfoot",
  "Old Scrape",
  "Stone Lip",
  "Dry Knuckle",
  "Pit Roach",
  "Thornjaw",
  "Copper Nose",
  "Cracked Milo",
  "Lowborn Takk",
  "Arena Midge",
  "Cassian",
  "Brutus",
  "Valco",
  "Drusus",
  "Marcell",
  "Tiber",
  "Lucan",
  "Aulus",
  "Septo",
  "Varro",
  "Corvin",
  "Flavius",
  "Marius",
  "Cato",
  "Gaius",
  "Decim",
  "Rufus",
  "Neroch",
  "Pullo",
  "Sulla",
  "Brog",
  "Hrokk",
  "Skarn",
  "Ulfan",
  "Grask",
  "Mord",
  "Tharn",
  "Krogga",
  "Vuld",
  "Brundir",
  "Orm",
  "Hagren",
  "Garv",
  "Drokk",
  "Kelgar",
  "Romb",
  "Skerd",
  "Varruk",
  "Nokkar",
  "Grimn",
  "Pug Marlo",
  "Bent Lars",
  "Tiny Voss",
  "Big Nib",
  "One-Tooth Rem",
  "Limp Dravo",
  "Sour Klem",
  "Red-Eye Pott",
  "Nervous Gann",
  "Lucky Noll",
  "Flat Helm",
  "Short Fuse",
  "Bad Elbow",
  "Crooked Sandro",
  "Wrong Marcus",
  "Iron Veso",
  "Black Brakk",
  "Thorn Marius",
  "Dread Varro",
  "Hookhand",
  "Skull Tiber",
  "Blood Cassian",
  "Chain Rufus",
  "Spear Nemm",
  "Ash Corvin",
  "Bone Drusus",
  "Red Sulla",
  "Stone Krog",
  "Pit Butcher",
  "Vark Splitter",
  "Lucan No-Mercy",
  "Grask Halfshield",
  "Brundir Heavy",
  "Marcell Quiet",
  "Tull Blackgrin",
  "Borvak Wall",
  "Cassian Iron Palm",
  "Rufus Red Pit",
  "Valco Chainbreaker",
  "Marius Sand-King",
  "Skarn Bonehelm",
  "Brakk Unfed",
  "Tiber Nine-Scars",
  "Orlo Collector",
  "Drusus Wolf-Blood",
  "Hrokk Arena-Eater",
  "Varro Patient",
  "Klem Hook",
  "Corvin Black Banner",
  "Ragged Aulus",
  "Splinter Gaius",
  "Furnace Cato",
  "Bitter Pullo",
  "Yellow Septo",
  "Fallow Decim",
  "Clawhand Mott",
  "Old Narg",
  "Rusk of Ash",
  "Palk the Thin",
  "Bendo the Loud",
  "Harn the Bent",
  "Farlo Two-Knives",
  "Skiv Lowstep",
  "Dott No-Teeth",
  "Marn Red Sand",
  "Veso Half-Helm",
  "Brakk Lowborn",
  "Tull Sour-Blood",
  "Gann of the Pit",
  "Nemm Dustcloak",
  "Vark Brassjaw",
  "Brog Chainleg",
  "Hrokk the Slow",
  "Skarn Redhand",
  "Ulfan Stonegut",
  "Mord Cutbrow",
  "Tharn Pig-Iron",
  "Krogga Ash-Tongue",
  "Vuld the Narrow",
  "Brundir Oathless",
  "Orm the Damp",
  "Hagren Old Scar",
  "Garv Mud-King",
  "Drokk Far-Eye",
  "Kelgar Flatfoot",
  "Romb Ironbelly",
  "Skerd the Pale",
  "Varruk Thickneck",
  "Nokkar Bonewise",
  "Grimn Cold-Ear",
  "Dusty Marcell",
  "Rufus Hooknose",
  "Cassian Dull Blade",
  "Varro Sand-Lung",
  "Lucan Bent Spear",
  "Marius Old Coin",
  "Flavius Mudsong",
  "Drusus Hardbread",
  "Cato Tin-Shield",
  "Septo Bittercup",
  "Decim Crow-Helm",
  "Aulus Red Rope",
  "Sulla Dry-Eye",
  "Corvin Thorncoat",
  "Neroch Black Tooth",
  "Pullo Low Smoke",
  "Brutus Salt-Wound",
  "Valco Deadpan",
  "Tiber Iron Knee",
  "Marcell Bad Luck",
  "Sandro Goat-Step",
  "Milo Broken Cup",
  "Takk Candle-Eater",
  "Pott Mild Terror",
  "Rem the Wobbly",
  "Nib Copperbelly",
  "Voss Knee-Biter",
  "Lars Mudface",
  "Noll Barefoot",
  "Jax Sootmouth",
  "Tom Two-Bricks",
  "Scrape",
  "Paver",
  "Ashnose",
  "Boneheel",
  "Rattle Klem",
  "Mugwort Marn",
  "Bellow Gann",
  "Cramp Veso",
  "Splint Rusk",
  "Sour Orlo",
  "Mad Dott",
  "Snaggle Tull",
  "Cinder Brakk",
  "Whetstone Vark",
  "Iron Dott",
  "Red Klem",
  "Black Narg",
  "Low Marius",
  "Old Cassian",
  "Mud Varro",
  "Pit Gaius",
  "Ash Rufus",
  "Copper Drusus",
  "Dust Lucan",
  "Chain Cato",
  "Spear Pullo",
  "Stone Brutus",
  "Gravel Flavius",
  "Thorn Neroch",
  "Bone Sulla",
  "Rust Decim",
  "Dry Aulus",
  "Hook Septo",
  "Cracked Corvin",
] as const;
