import {
  FIGHTER_BACK_BOOT_LIGHT_ASSET_URL,
  FIGHTER_BACK_GAUNTLET_LIGHT_ASSET_URL,
  FIGHTER_BACK_GREAVE_LIGHT_ASSET_URL,
  FIGHTER_BACK_SHINGUARD_LIGHT_ASSET_URL,
  FIGHTER_BACK_SHOULDERGUARD_LIGHT_ASSET_URL,
  FIGHTER_BREASTPLATE_LIGHT_ASSET_URL,
  FIGHTER_FRONT_BOOT_LIGHT_ASSET_URL,
  FIGHTER_FRONT_GAUNTLET_LIGHT_ASSET_URL,
  FIGHTER_FRONT_GREAVE_LIGHT_ASSET_URL,
  FIGHTER_FRONT_SHINGUARD_LIGHT_ASSET_URL,
  FIGHTER_FRONT_SHOULDERGUARD_LIGHT_ASSET_URL,
  FIGHTER_HELMET_LIGHT_ASSET_URL,
  FIGHTER_WEAPON_SWORD_01_ASSET_URL,
} from "./assets";
import {
  STARTER_BACK_BOOT_ID,
  STARTER_BACK_GAUNTLET_ID,
  STARTER_BACK_GREAVE_ID,
  STARTER_BACK_SHINGUARD_ID,
  STARTER_BACK_SHOULDERGUARD_ID,
  STARTER_BREASTPLATE_ID,
  STARTER_FRONT_BOOT_ID,
  STARTER_FRONT_GAUNTLET_ID,
  STARTER_FRONT_GREAVE_ID,
  STARTER_FRONT_SHINGUARD_ID,
  STARTER_FRONT_SHOULDERGUARD_ID,
  STARTER_HELMET_ID,
  TRAINING_WEAPON_ID,
  type HeroItemId,
} from "./hero";
import { GENERATED_EQUIPMENT_ITEM_RECORDS } from "./generated/equipmentItems.generated";

const SHOP_ITEM_ICON_URLS: Partial<Record<HeroItemId, string>> = {
  [TRAINING_WEAPON_ID]: FIGHTER_WEAPON_SWORD_01_ASSET_URL,
  [STARTER_HELMET_ID]: FIGHTER_HELMET_LIGHT_ASSET_URL,
  [STARTER_BREASTPLATE_ID]: FIGHTER_BREASTPLATE_LIGHT_ASSET_URL,
  [STARTER_BACK_SHOULDERGUARD_ID]: FIGHTER_BACK_SHOULDERGUARD_LIGHT_ASSET_URL,
  [STARTER_FRONT_SHOULDERGUARD_ID]: FIGHTER_FRONT_SHOULDERGUARD_LIGHT_ASSET_URL,
  [STARTER_BACK_GAUNTLET_ID]: FIGHTER_BACK_GAUNTLET_LIGHT_ASSET_URL,
  [STARTER_FRONT_GAUNTLET_ID]: FIGHTER_FRONT_GAUNTLET_LIGHT_ASSET_URL,
  [STARTER_BACK_GREAVE_ID]: FIGHTER_BACK_GREAVE_LIGHT_ASSET_URL,
  [STARTER_FRONT_GREAVE_ID]: FIGHTER_FRONT_GREAVE_LIGHT_ASSET_URL,
  [STARTER_BACK_SHINGUARD_ID]: FIGHTER_BACK_SHINGUARD_LIGHT_ASSET_URL,
  [STARTER_FRONT_SHINGUARD_ID]: FIGHTER_FRONT_SHINGUARD_LIGHT_ASSET_URL,
  [STARTER_BACK_BOOT_ID]: FIGHTER_BACK_BOOT_LIGHT_ASSET_URL,
  [STARTER_FRONT_BOOT_ID]: FIGHTER_FRONT_BOOT_LIGHT_ASSET_URL,
  ...Object.fromEntries(GENERATED_EQUIPMENT_ITEM_RECORDS.map((record) => [record.item.id, record.asset.url])),
};

export function getShopProductIconUrl(itemIds: HeroItemId[]): string | undefined {
  const representativeItemId = [...itemIds].reverse().find((itemId) => SHOP_ITEM_ICON_URLS[itemId]);

  return representativeItemId ? SHOP_ITEM_ICON_URLS[representativeItemId] : undefined;
}
