/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/forest-forge/wrangler.jsonc --include-runtime=false workers/forest-forge/worker-configuration.d.ts` (hash: 50c8cd8f9e2341d0a1dc1df9d555a234)
interface __BaseEnv_Env {
	SAVES: D1Database;
	ASSETS: Fetcher;
	BOT_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BOT_TOKEN">> {}
}
