// Small DOM boundary double: native text setters coerce values, and clicks bubble through closest().
// It models only the elements generated by the hero panel; browser QA covers real parsing/layout.
export function createHeroFixture(createHeroUI, hero, initialBattle = null) {
  let writes = 0, stopped = 0, closed = 0, battle = initialBattle;
  const changes = [];
  class Node {
    constructor(parent = null, selector = '') {
      this.parent = parent; this.selector = selector; this.children = new Map(); this.nodes = [];
      this.attributes = new Map(); this.listeners = new Map(); this.dataset = {}; this.style = {};
      this.hidden = false; this.disabled = false; this.title = ''; this.text = ''; this.html = '';
      this.classes = new Set();
      this.classList = {
        add: (...names) => { names.forEach(name => this.classes.add(name)); writes++; },
        toggle: (name, force) => { if (force) this.classes.add(name); else this.classes.delete(name); writes++; return !!force; },
      };
    }
    set textContent(value) { this.text = value == null ? '' : String(value); writes++; }
    get textContent() { return this.text; }
    set innerHTML(value) {
      this.html = value; writes++;
      if (value.includes('hero-trigger-level')) {
        this.child('.hero-trigger-level'); this.child('.hero-trigger-points');
      } else if (value.includes('hero-card')) {
        for (const name of ['level', 'points', 'xp', 'stats', 'timing', 'detail-name', 'detail-rank', 'detail-description',
          'detail-gate', 'spend', 'reset', 'reset-hint']) this.child(`[data-hero-${name}]`);
        this.child('[data-close-overlay]');
        this.child('.hero-detail-empty'); this.child('.hero-detail-content');
        this.child('.hero-xp-track').firstElementChild = new Node(this);
        for (const match of value.matchAll(/data-hero-talent="([^"]+)"/g)) {
          const talent = new Node(this, '[data-hero-talent]'); talent.dataset.heroTalent = match[1];
          talent.child('.hero-node-rank'); talent.child('.hero-node-gate'); this.nodes.push(talent);
        }
      }
    }
    get innerHTML() { return this.html; }
    child(selector) { const child = new Node(this, selector); this.children.set(selector, child); return child; }
    querySelector(selector) { return this.children.get(selector) ?? null; }
    querySelectorAll(selector) { return selector === '[data-hero-talent]' ? this.nodes : []; }
    setAttribute(name, value) { this.attributes.set(name, String(value)); writes++; }
    closest(selector) { return this.selector === selector ? this : this.parent?.closest(selector) ?? null; }
    addEventListener(event, listener) { const listeners = this.listeners.get(event) ?? new Set(); listeners.add(listener); this.listeners.set(event, listeners); }
    removeEventListener(event, listener) { this.listeners.get(event)?.delete(listener); }
  }
  const button = new Node(), panel = new Node();
  const ui = createHeroUI({ button, panel, getHero: () => hero, getBattle: () => battle,
    onChange: change => changes.push(change), close: () => { closed++; } });
  const click = (target, nested = false) => {
    const event = { target: nested ? new Node(target) : target, stopPropagation() { stopped++; } };
    for (const listener of [...(panel.listeners.get('click') ?? [])]) listener(event);
  };
  const ref = name => panel.querySelector(`[data-hero-${name}]`);
  const select = id => click(panel.nodes.find(node => node.dataset.heroTalent === id), true);
  const describe = node => ({ text: node.textContent, hidden: node.hidden, disabled: node.disabled,
    classes: [...node.classes], attributes: [...node.attributes], dataset: node.dataset, style: node.style });
  return { ui, button, panel, hero, changes, click, select, ref, setBattle(value) { battle = value; },
    get writes() { return writes; }, get stopped() { return stopped; }, get closed() { return closed; },
    snapshot() { return structuredClone({ hero, changes, stopped, closed, button: { ...describe(button), title: button.title, html: button.innerHTML,
      children: [...button.children].map(([key, node]) => [key, describe(node)]) },
      panel: { ...describe(panel), html: panel.innerHTML, listeners: panel.listeners.get('click')?.size ?? 0,
        children: [...panel.children].map(([key, node]) => [key, describe(node)]),
        nodes: panel.nodes.map(node => ({ ...describe(node), children: [...node.children].map(([key, child]) => [key, describe(child)]) })),
        xpWidth: panel.querySelector('.hero-xp-track').firstElementChild.style.width } }); },
  };
}
