const {chromium,webkit}=require('C:/Users/Waldiris/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const p=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});const errors=[];
p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400&&r.url().includes('127.0.0.1'))errors.push(r.status()+' '+r.url())});
await p.goto('http://127.0.0.1:4176/?dungeons=1&debug=1');await p.waitForFunction(()=>!!window.__forestForge);await p.waitForTimeout(300);
// Isolated browser save: use upgraded green gear for the stronger dungeon curve.
await p.evaluate(async()=>{const {SAVE_KEY,stats}=await import('./game.mjs');const s=window.__forestForge.snapshot();for(const item of Object.values(s.equipment)){item.value=Math.round(item.value*1.2);item.itemLevel=5;}s.hp=stats(s).hp;localStorage.setItem(SAVE_KEY,JSON.stringify(s));});
await p.goto('http://127.0.0.1:4176/?debug=1');await p.waitForFunction(()=>!!window.__forestForge);await p.locator('#dungeons-toggle').click();
assert.deepEqual(await p.locator('.dungeon-card-cleared').allTextContents(),['1–10','1–10','1–10']);
await p.screenshot({path:'forest-forge/design/dungeons/hub.png'});
assert.equal(await p.locator('#dungeon-hub .mount-reward-row').count(),0);
await p.locator('#tier-rewards-toggle').click();
assert.ok(await p.locator('#mount-condition').isVisible());assert.ok(await p.locator('#mount-action').isHidden());
await p.screenshot({path:'forest-forge/design/dungeons/tier-rewards-locked.png'});
await p.keyboard.press('Escape');assert.ok(await p.locator('#dungeon-hub').isVisible());
for(let i=0;i<3;i++){
 await p.locator('.dungeon-card-action button').nth(i).click();
 assert.equal(await p.locator('#dungeon-floor').textContent(),'Stage 1–10');
 assert.equal(await p.locator('#dungeon-rewards > span').count(),1);
 await p.locator('#dungeon-fight').click();await p.waitForFunction(()=>!!window.__forestForge.snapshot().dungeons.run);
 await p.waitForTimeout(300);await p.evaluate(()=>window.__forestForge.advance(12));await p.waitForTimeout(150);
 await p.screenshot({path:`forest-forge/design/dungeons/fight-${i}.png`});
 const destination=await p.locator(['.money > .coin','.hammer-balance > .hammer-icon','#mine-toggle img'][i]).first().boundingBox();
 const before=await p.evaluate(()=>{const s=window.__forestForge.snapshot();return {coins:s.coins,hammers:s.hammers,ore:s.mine.ore,loot:s.dungeons.run.rewards};});
 assert.equal(await p.evaluate(()=>{window.__forestForge.advance(90);return window.__forestForge.snapshot().dungeons.last?.outcome;}),'won');
 await p.waitForSelector('.dungeon-reward-burst');
 await p.evaluate(()=>document.getElementById('reward-flight').getAnimations({subtree:true}).forEach(a=>{a.pause();a.currentTime=650;}));
 assert.equal(await p.locator('#dungeon-result').count(),0);
 assert.ok(await p.locator('#dungeon-hub').isVisible());assert.ok(await p.locator('.reward-particle').count()>0);
 assert.equal(await p.locator('.dungeon-stocks').count(),0);
 const flight=await p.locator('.reward-particle').first().evaluate(el=>{const k=el.getAnimations()[0].effect.getKeyframes().at(-1),m=new DOMMatrix(k.transform),r=el.parentElement.getBoundingClientRect();return {x:m.m41+el.offsetWidth/2+r.x,y:m.m42+el.offsetHeight/2+r.y};});
 assert.ok(Math.abs(flight.x-destination.x-destination.width/2)<1);assert.ok(Math.abs(flight.y-destination.y-destination.height/2)<1);
 await p.screenshot({path:`forest-forge/design/dungeons/result-${i}.png`});
 await p.evaluate(()=>document.getElementById('reward-flight').getAnimations({subtree:true}).forEach(a=>a.finish()));
 await p.waitForFunction(()=>!document.getElementById('game').inert);
 const after=await p.evaluate(()=>window.__forestForge.snapshot());
 assert.equal(after.coins,before.coins+before.loot.coins);assert.equal(after.hammers,before.hammers+before.loot.hammers);
 assert.deepEqual(after.mine.ore,before.ore.map((n,j)=>n+(before.loot.ore[j]||0)));assert.equal(after.dungeons.last,null);
 assert.equal(await p.locator('.reward-particle').count(),0);
}
assert.equal(await p.locator('dialog[open]').count(),0);await p.locator('#tier-rewards-toggle').click();await p.locator('#tier-rewards-dialog[open]').waitFor();
assert.ok(await p.locator('#tier-rewards-toggle').evaluate(e=>e.classList.contains('has-reward')));
await p.locator('#mount-action').click();assert.equal(await p.evaluate(()=>window.__forestForge.snapshot().mount.equipped),true);
assert.equal(await p.locator('#tier-rewards-toggle').evaluate(e=>e.classList.contains('has-reward')),false);
await p.locator('#mount-action').click();assert.equal(await p.evaluate(()=>window.__forestForge.snapshot().mount.equipped),false);
await p.locator('#mount-action').click();assert.equal(await p.evaluate(()=>window.__forestForge.snapshot().mount.equipped),true);
await p.screenshot({path:'forest-forge/design/dungeons/tier-rewards-owned.png'});
await p.locator('#close-tier-rewards').click();
await p.locator('#dungeons-toggle').click();await p.waitForTimeout(1200);
await p.screenshot({path:'forest-forge/design/dungeons/mounted.png'});
const saved=await p.evaluate(()=>window.__forestForge.snapshot());
await p.evaluate(async s=>{const {SAVE_KEY}=await import('./game.mjs');localStorage.setItem(SAVE_KEY,JSON.stringify(s));},saved);
await p.goto('http://127.0.0.1:4176/?debug=1');await p.waitForFunction(()=>!!window.__forestForge);
assert.equal(await p.evaluate(()=>window.__forestForge.snapshot().mount.equipped),true);
assert.deepEqual(await p.evaluate(()=>window.__forestForge.snapshot().dungeons.cleared),[10,10,10]);
await p.locator('#dungeons-toggle').click();await p.locator('.dungeon-card-action button').first().click();
assert.deepEqual(await p.locator('.dungeon-card-cleared').allTextContents(),['2–1','2–1','2–1']);
assert.equal(await p.locator('#dungeon-floor').textContent(),'Stage 2–1');
assert.equal(await p.locator('#dungeon-rewards > span').count(),1);
 await p.locator('#dungeon-fight').click();await p.waitForFunction(()=>!!window.__forestForge.snapshot().dungeons.run);await p.evaluate(()=>window.__forestForge.advance(8));await p.waitForTimeout(200);
await p.screenshot({path:'forest-forge/design/dungeons/mounted-battle.png'});
await p.reload();await p.waitForFunction(()=>!!window.__forestForge);await p.waitForFunction(()=>!document.getElementById('game').inert&&!document.getElementById('dungeon-hub').hidden);
assert.equal(await p.evaluate(()=>window.__forestForge.snapshot().dungeons.last),null);
assert.deepEqual(await p.evaluate(()=>window.__forestForge.snapshot().dungeons.wins),[1,1,1]);
assert.equal(await p.locator('.reward-particle').count(),0);
await p.setViewportSize({width:360,height:640});await p.waitForTimeout(200);
await p.screenshot({path:'forest-forge/design/dungeons/hub-small.png'});
await p.locator('#tier-rewards-toggle').click();
assert.equal(await p.locator('#mount-action').textContent(),'Dismount');
await p.screenshot({path:'forest-forge/design/dungeons/tier-rewards-small.png'});
await p.locator('#close-tier-rewards').click();
const nav=await p.locator('#activities').boundingBox();assert.ok(nav.y+nav.height<=640.1);
const back=await p.locator('#dungeon-hub-back').boundingBox();assert.ok(back.y+back.height<=nav.y&&nav.y-back.y-back.height<=16);
await p.locator('.dungeon-card-action button').nth(2).click();await p.waitForFunction(()=>document.getElementById('dungeon-boss-art').complete&&document.getElementById('dungeon-boss-art').naturalWidth>0);await p.screenshot({path:'forest-forge/design/dungeons/detail-small.png'});
assert.deepEqual(errors,[]);console.log('Chromium: three automatic reward returns, exact resource credit, claim, mounted fight, save/reload, interrupted run and small viewport passed.');
await browser.close();
const wb=await webkit.launch({headless:true});const wp=await wb.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});const we=[];wp.on('pageerror',e=>we.push(e.message));
await wp.goto('http://127.0.0.1:4176/?dungeons=1&debug=1');await wp.waitForFunction(()=>!!window.__forestForge);
await wp.setViewportSize({width:320,height:640});await wp.locator('#tier-rewards-toggle').click();
await wp.screenshot({path:'forest-forge/design/dungeons/tier-rewards-webkit-320.png'});
assert.ok(await wp.locator('#tier-rewards-dialog').evaluate(e=>e.scrollWidth<=e.clientWidth));
await wp.locator('#close-tier-rewards').click();await wp.setViewportSize({width:390,height:844});
await wp.locator('.dungeon-card-action button').first().click();await wp.locator('#dungeon-fight').click();await wp.waitForFunction(()=>!!window.__forestForge.snapshot().dungeons.run);await wp.evaluate(()=>window.__forestForge.advance(12));await wp.waitForTimeout(200);await wp.screenshot({path:'forest-forge/design/dungeons/webkit-battle.png'});assert.deepEqual(we,[]);await wb.close();console.log('WebKit: 320px tier rewards, hub, entry and battle passed.');
})().catch(e=>{console.error(e);process.exit(1)});
